# Site settings
title: Dan Hodges
email: dhdgs690@gmai.com
description: > # this means to ignore newlines until "baseurl:"
  I am a recent graduate of Nashville Software School. After an intense six-month apprenticeship, I am seeking to join a solid team of software developers in the Nashville area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.dan-hodges.com" # the base hostname & protocol for your site
twitter_username: _DanHodges
github_username:  DanHodges

title : Dan Hodges
tagline: Site Tagline
author :
  name : Dan Hodges
  email : dhdgs690@gmail.com
  github : DanHodges
  twitter : _DanHodges


# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Home
    link: http://www.dan-hodges.com
  option2:
    name: Resume
    link: site/2015/12/12/resume.html
  option3:
    name: GitHub
    link: https://github.com/DanHodges
  option4:
    name: About
    link: http://www.dan-hodges.com  

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
