# Site settings
title: Dan Hodges
email: dhdgs690@gmai.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.dan-hodges.com" # the base hostname & protocol for your site
twitter_username: _DanHodges
github_username:  DanHodges

title : Dan Hodges
tagline: Site Tagline
author :
  name : Dan Hodges
  email : dhdgs690@gmail.com
  github : DanHodges
  twitter : _DanHodges


# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Home
    link: www.myawesomelink.com
  option2:
    name: Resume
    link: www.myawesomelink.com
  option3:
    name: GitHub
    link: www.myawesomelink.com
  option4:
    name: About
    link: www.myawesomelink.com  

disqus: false
disqus_shortname: 'gdgmanagua'

# Build settings
markdown: kramdown
